# release action with semantic release
name: Release github version

on:
  push:
    branches:
      - release

jobs:
  release:
    name: Release to
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm ci
        # Here commit and push the updated files
      - name : Semantic release
        run: npx semantic-release
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      # - name: Update packages
      #   run: npm i
      # - name: Commit and push changes
      #   run: |
      #       git config --global user.email "nunes.clement19@gmail.com"
      #       git config --global user.name "NunesClement"
      #       git add .
      #       git commit -m "chore(app): bump versions"
      #       git push origin release